language: perl

perl:
    - "5.22"

services:
    - redis-server

env:
    global:
        - RELEASE_TESTS=1

cache:
    directories:
        - perl_modules

before_install:
    - cpanm local::lib
    - eval "$(perl -Mlocal::lib=${PWD}/perl_modules)"
    - cpanm --notest Test::Distribution
    - cpanm --notest Test::Kwalitee
    - cpanm --notest Test::Kwalitee::Extra

