---
abstract: 'Redis::JobQueue simple job queue with Redis server capabilities.'
author:
  - 'TrackingSoft LLC <sgladkov@trackingsoft.com>'
build_requires:
  Net::EmptyPort: 0
  Test::Deep: 0.109
  Test::Exception: 0.31
  Test::NoWarnings: 1.04
  Test::RedisServer: 0.04
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.8, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Redis-JobQueue
no_index:
  directory:
    - t
    - inc
    - xt
    - ex
provides:
  Redis::JobQueue:
    file: lib/Redis/JobQueue.pm
    version: 1.08
  Redis::JobQueue::Job:
    file: lib/Redis/JobQueue/Job.pm
    version: 1.07
requires:
  Data::UUID: 1.217
  Digest::SHA1: 2.13
  List::MoreUtils: 0.33
  Mouse: 0.97
  Params::Util: 1.07
  Redis: 1.963
  Storable: 2.39
  Try::Tiny: 0.18
  perl: 5.010
version: 1.08
