---
abstract: 'Redis::JobQueue simple job queue with Redis server capabilities.'
author:
  - 'TrackingSoft LLC <sgladkov@trackingsoft.com>'
build_requires:
  Test::Distribution: 2
  Test::Exception: 0.31
  Test::Fixme: 0.07
  Test::Kwalitee: 1.01
  Test::Perl::Critic: 1.02
  Test::Pod: 1.45
  Test::Pod::Coverage: 1.08
  Test::RedisServer: 0.04
  Test::TCP: 1.17
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Redis-JobQueue
no_index:
  directory:
    - t
    - inc
requires:
  Data::UUID: 1.217
  Mouse: 0.97
  Params::Util: 1.07
  Redis: 1.926
version: 0.03
